name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI checks

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14, 16, 18 ]

    steps:
      - uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/test
        with:
          coverage: 1
          node-version: ${{ matrix.node-version }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
